### ISSUE TITLE
pycp2110 on windows, import hid Cann't load many dll files

### ISSUE THREAD

**Issue by finethegap** [rginda/pycp2110#2]
Hi, I want help in using pycp2110. I am using Spyder via Anaconda on Windows 10. When I use this module, the error shows it can't load a few of dll files.

**Comment by rginda** [comment]
Sorry, I've never use Spyder or Anaconda.  The pycp2110 library is pure Python and has no DLLs, so whatever problem you're having it's not related to this code.
